# netlify.toml - Netlify configuration file
[build]
  publish = "/"
  command = "# no build command needed for static site"

# Redirect /admin to /admin/index.html
[[redirects]]
  from = "/admin"
  to = "/admin/index.html"
  status = 200